test:
  foreign_server:
    host: localhost
    port: 5432
    database: foreign_db
    user: foreign_user
    password: password
    fetch_size: 50 # default value explicitly

integration_test:
  foreign_server:
    host: localhost
    port: 5432
    database: foreign_db
    user: foreign_user
    password: password
    fetch_size: 50 # default value explicitly
